### ISSUE TITLE
charm won't deploy with current owncloud repo (v10)

### ISSUE THREAD

**Issue by kwmonroe** [omnivector-solutions/layer-owncloud#1]
Owncloud split into a meta package, -files, and -deps around v9:

https://doc.owncloud.org/server/10.0/admin_manual/installation/linux_installation.html

But in the default production repo configured by this charm layer (v10), it seems they no longer supply the `owncloud` metapackage:

```bash
$ apt-cache search owncloud | grep ^own
owncloud-client - folder synchronization with an ownCloud server - GUI
owncloud-client-cmd - folder synchronization with an ownCloud server - cmd client
owncloud-client-doc - ownCloudSync folder synchronization - documentation
owncloud-client-l10n - ownCloudSync folder synchronization - localization
owncloud-doc - documentation for ownCloud
owncloud-files - ownCloud - Server
```

This causes the installation to hang:

```
$ juju debug-log -i ownbdx/0
unit-ownbdx-0: 10:51:36 DEBUG unit.ownbdx/0.update-status Building dependency tree...
unit-ownbdx-0: 10:51:36 DEBUG unit.ownbdx/0.update-status Reading state information...
unit-ownbdx-0: 10:51:36 DEBUG unit.ownbdx/0.update-status Package owncloud is not available, but is referred to by another package.
unit-ownbdx-0: 10:51:36 DEBUG unit.ownbdx/0.update-status This may mean that the package is missing, has been obsoleted, or
unit-ownbdx-0: 10:51:36 DEBUG unit.ownbdx/0.update-status is only available from another source
unit-ownbdx-0: 10:51:36 DEBUG unit.ownbdx/0.update-status However the following packages replace it:
unit-ownbdx-0: 10:51:36 DEBUG unit.ownbdx/0.update-status   owncloud-files
unit-ownbdx-0: 10:51:36 DEBUG unit.ownbdx/0.update-status
unit-ownbdx-0: 10:51:36 DEBUG unit.ownbdx/0.update-status E: Package 'owncloud' has no installation candidate
unit-ownbdx-0: 10:51:37 WARNING unit.ownbdx/0.juju-log blocked: Unable to install packages owncloud
```

Simplest fix would be to set the default repo to v9 in `config.yaml` (which still includes the `owncloud` metapackage, which gets all the files and deps installed):

```yaml
    default: |
      - "deb http://download.owncloud.org/download/repositories/9.0/Ubuntu_16.04/ /"
```

If you're set on staying with v10, this might be fixable in `layer.yaml` by being explicit with all the pkgs that we need from -deps, as well as `owncloud-files`:

```yaml
options:
  apt:
    packages:
      - owncloud-files
      - apache2
      - mariadb-server
      - libapache2-mod-php7.0
      - php7.0-gd
      - php7.0-json
      - php7.0-mysql
      - php7.0-curl
      - php7.0-intl
      - php7.0-mcrypt
      - php-imagick
      - php7.0-zip php7.0-xml
      - php7.0-mbstring
```

Note, the above comes from https://doc.owncloud.org/server/10.0/admin_manual/installation/source_installation.html#ubuntu-installation-label. The problem now is that you don't get any of the postinst bits that the `owncloud` metapackage provided, so you'd have to setup an apache vhost and configure the local db in the charm.

As i mentioned, defaulting to v9 is the quick fix, but I'll leave it up to you with how robust you want this sucker to be ;)

**Comment by jamesbeedy** [comment]
@kwmonroe  ahh, sorry, I shouldn't of released this thing in its current condition.

I've put in a few cycles here, let me know if this works for you?

```yaml
series: xenial
applications:
  postgresql:
    charm: 'cs:postgresql'
    num_units: 1
  owncloud:
    charm: 'cs:~omnivector/owncloud'
    num_units: 1
    options:
      admin-username: "admin"
      admin-password: "mypassword"
    expose: true
relations:
  - - 'postgresql:db'
    - 'owncloud:postgresql'
```
