### ISSUE TITLE
active status isn't set

### ISSUE THREAD

**Issue by kwmonroe** [omnivector-solutions/layer-owncloud#2]
I may be missing something, but i don't see how `layer-owncloud.installed` ever gets set:

https://github.com/jamesbeedy/layer-owncloud/blob/master/reactive/layer_owncloud.py#L14

That means the `active` status never gets set, which leaves the deployment like this forever:

```
Unit         Workload     Agent  Machine  Public address  Ports   Message
owncloud/0*  maintenance  idle   0        52.87.157.214   80/tcp  Installing owncloud
```

**Comment by jamesbeedy** [comment]
@kwmonroe oh hey, thanks for pointing this out.

**Comment by jamesbeedy** [comment]
@kwmonroe the reason this happened is because Owncloud's install procedure/maintained packages changed.

Also, sorry to swap this repo out from underneath you to a different org, but I thought this would be a good time to do it.


The install ops for owncloud (at a most basic level) use to just be 

1) add the source repo
2) `apt install owncloud`

With the latest Owncloud 10.x.x, the install process entails slightly more ops, including installing a package `owncloud-files` and following which running a few install commands (not sure I have exhausted all of these install ops).

Either way, this charm needed some love. Not sure its quite "production ready", but its deploying and operating successfully now to some extent.

I've added a TODO in the README.md with some forward thinking dev for this charm.

Let me know if this works for you
```yaml
series: xenial
applications:
  postgresql:
    charm: 'cs:postgresql'
    num_units: 1
  owncloud:
    charm: 'cs:~omnivector/owncloud'
    num_units: 1
relations:
  - - 'postgresql:db'
    - 'owncloud:postgresql'
```
